### PR TITLE
Pexpect

### PR DESCRIPTION
**Pull request by kaho1910**

### CODE REVIEW

**Comment by whitewolf5432** [comment]
Why you not add .gitignore for ignore environment resources because other peoples can install this environment by themself.

**Comment by kaho1910** [comment]
I just added .gitginore, please review it again.

**Comment by whitewolf5432** [comment]
Great job, I think it better than previous version and so more clean.

**Review by whitewolf5432 — APPROVED** [review]
👍: Approve, I like your request

**Pull request merged**
